[package]
name = "click-path"
version = "0.1.0"
edition = "2024"

[dependencies]
win-hotkeys = "0.5.0"
enigo = "0.3.0"
crossbeam-channel = "0.5.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"